version: '3.8'

services:
  4hv:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db-4hv
  db-4hv:
    image: postgres:17
    volumes:
      - 4hv-pgdata:/var/lib/postgresql/data

volumes:
  4hv-pgdata:
